### ISSUE TITLE
High cpu and ram usage

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [serversideup/webext-bridge#62]
![图片](https://github.com/zikaari/webext-bridge/assets/52521836/a6cfc605-b96b-428e-9dd6-cba32578bdb3)

I don't know what's going on internally, but when I remove all code that references `webext-bridge`, cpu and ram usage will normal
![图片](https://github.com/zikaari/webext-bridge/assets/52521836/f95b9328-14a7-45c3-b196-64102a046fe3)

I use firefox, the following is a profile all threads of process for 5 seconds, hope to help you
https://share.firefox.dev/3oMZ9Z9

**Comment by SevrainChea** [comment]
Hello @WOSHIZHAZHA120 , We are facing some performance/memory leak issues in my company with our chrome-extension. I have been investigating possible candidates, when I stumbled on your issue. 
Why did you close it ? Did you rule out this lead ?

**Comment by WOSHIZHAZHA120** [comment]
> Hello @WOSHIZHAZHA120 , We are facing some performance/memory leak issues in my company with our chrome-extension. I have been investigating possible candidates, when I stumbled on your issue. Why did you close it ? Did you rule out this lead ?

I've been troubleshooting the problem for a long time, and finally realized that it was my fault, I wrapped a Message class, which has a `send` method, the `send` method imports `sendMessage` from `webext-bridge/content-script`, and the background script imports `onMessage` from `webext-bridge/background`, which might be conflicting, and causing me to get high on CPU and RAM very quickly.
