### ISSUE TITLE
Project unmaintained - looking for maintainers

### ISSUE THREAD

**Issue by zikaari** [serversideup/webext-bridge#72]
While this project has served its purpose well for many users, I regret to inform you that due to constraints on my time and resources, I am no longer able to support or maintain this project. Consequently, existing and potential issues may remain unresolved.

I am reaching out to the vibrant webext-bridge community in the hopes of finding dedicated maintainers who possess a strong understanding of Chrome extension APIs and the intricate interactions within the project. Your commitment will be crucial in addressing both past and future issues, ensuring the continued success of this project.

If you are passionate about webext-bridge and have the expertise to contribute, please express your interest by reacting with a 🚀 to this message. I am actively looking to add collaborators who can invest their time and skills to keep this project thriving.

Stay tuned for more details on how you can become a collaborator and contribute to the longevity of webext-bridge.

Thank you for your understanding and continued support.

**Comment by danpastori** [comment]
Hi @zikaari ,

I'd love to chat more and maintain this project! We really enjoy the package and appreciate your contribution. The package is a core part of the book that I wrote about Building Multi-Platform Browser Extensions: https://serversideup.net/building-multi-platform-browser-extensions/

I even wrote an extended blog post here: https://serversideup.net/browser-extension-messaging/

We manage quite a few internal open-source projects such as:

- Docker PHP: https://serversideup.net/open-source/docker-php/
- AmplitudeJS (a JS Audio Framework): https://github.com/serversideup/amplitudejs
- Spin: https://serversideup.net/open-source/spin/
- Financial Freedom: https://serversideup.net/open-source/financial-freedom/

We'd love to write updated docs like we did for our other open source projects and keep maintaining and expanding upon your work.

Feel free to shoot me a DM on Twitter (https://twitter.com/danpastori) if you want to chat more!

**Comment by zikaari** [comment]
Hi @danpastori thank you for expressing interest in taking care of this package. Would you like to be added as a collaborator to this repo and explore how it works out?

**Comment by danpastori** [comment]
Awesome, thanks!

We have an active community with @serversideup, so our long term goal would be to transfer the repository over to Server Side Up so it can be included with the rest of our open source projects.

The biggest things that I will improve on for this project is:

1. Create a documentation engine (like what we did for Spin [Spin](https://serversideup.net/open-source/spin/))
1. Fix a number of bugs reported in the [issues](https://github.com/zikaari/webext-bridge/issues)
1. Improve the developer experience with debugging issues

Let me know your thoughts on what's best for moving forward. We can chat more on Discord or something if you'd like too.

**Comment by zikaari** [comment]
That works for me as well, I'll initiate the transfer later today.

**Comment by danpastori** [comment]
Thanks so much! I got the transfer initiated. Looking forward to continue what you started. It's an awesome project!

**Comment by jaydrogers** [comment]
@zikaari: Thanks for working with Dan on transferring the repository. We're excited to carry the torch of your great work into the next chapter.

**Invite to NPM**
Are you also able to invite us as maintainers to the NPM package so we can publish updates?

https://www.npmjs.com/package/webext-bridge
Our usernames are:
- jaydrogers
- danpastori

**Comment by zikaari** [comment]
Glad to have you both onboard this ship. NPM invites sent.

Good luck and thank you!

**Comment by jaydrogers** [comment]
Thanks @zikaari! We'll take it from here! 🤝
