### ISSUE TITLE
Create landing page & docs site

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/webext-bridge#77]
![Image](https://github.com/serversideup/webext-bridge/assets/3174134/f4042b4a-d9c0-4d35-9e01-8f122af1ff6d)
## 🎨 Design Assets
https://www.figma.com/file/FGtJTt9r2mmEQKCRJwTNd9/webext-bridge-Designs?type=design&node-id=15120-421067&mode=design&t=pHsj203pK0G23q8j-11

## Hero
Special notes for the hero section:

### Navigation
- [x] Link to Discord
- [x] Link to GitHub
- [x] Use Nuxt search

### Docs
- [x] Use colors from `webext-bridge`, but use the styles from Docker PHP https://serversideup.net/open-source/docker-php/docs
- [x] @danpastori: You'll need to come up with some content to add to the documentation. Perhaps follow a structure similar to Spin? https://serversideup.net/open-source/spin/docs

### Hero
- [x] Link blue badge to book

## Professionally Supported
![Image](https://github.com/serversideup/webext-bridge/assets/3174134/5c669922-3015-4905-ab81-e5fd0576d4e4)

- [x] Link to the book
- [x] Professional support: Maybe link somewhere in the docs, that eventually links to our professional support calendar?
- [x] Community: Link to our GitHub Discussions

## FAQs
![Image](https://github.com/serversideup/webext-bridge/assets/3174134/f8f36c55-d8af-497f-ba03-9806a694f7f7)

- [x] Feel free to create content that answers the rest of the questions

## Building in Public
![Image](https://github.com/serversideup/webext-bridge/assets/3174134/b318b3c1-e233-4de6-b28e-32505d6d6327)

- [x] Connect our ConvertKit

## Footer
- [x] Link everything like our other projects

## Mobile
- [x] Ensure text sizes scale on mobile
- [x] Create mobile menus similar to our other projects
- [x] Scale things accordingly to the Figma document

**Comment by simonj** [comment]
Looks really good guys! who did the design 🙌

**Comment by jaydrogers** [comment]
Thanks!! We whipped it together in a day using components from Untitled UI (https://www.untitledui.com/).

It's a great kit to get something done quickly, but still have a custom build. It improves our two-person efficiency dramatically 😃
