### ISSUE TITLE
No tabId when receiving message in background from content-script

### ISSUE THREAD

**Issue by bogomazov** [serversideup/webext-bridge#87]
### Version

^6.0.1

### Current Behavior

sender in background onMessage has no tabId and frameId
<img width="225" alt="Screenshot 2024-05-15 at 13 06 37" src="https://github.com/serversideup/webext-bridge/assets/6625496/94a7347c-37b4-40b3-bcc9-4cc2cc458b8d">

### Expected Behavior

tabId and frameId to be present

### Steps To Reproduce

on Chrome. Create onMessage in background script and `await sendMessage(destination, data, "background")` from content script

**Comment by bogomazov** [comment]
now its working, idk why it was null at a time

**Comment by rocketdv** [comment]
How was this fixed, I'm still having this issue

**Comment by bogomazov** [comment]
turned out its there, just don't log the object itself (it erases these
values afterwards so it shows null in the console)

**Comment by seahindeniz** [comment]
I just faced the same issue. I have freeze the sender object via `Object.freeze` and traced back to the source. @bogomazov maybe it is fine to re-open the issue.
https://github.com/serversideup/webext-bridge/blob/main/src/background.ts#L160-L162

 I'm not sure why is it being overriden though. @zikaari maybe you can share some insights?
